### ISSUE TITLE
Error "_keys2 is not defined" when calling .getVue()

### ISSUE THREAD

**Issue by daenamkim** [DevExpress/testcafe-vue-selectors#52] opened 2021-04-19 04:00 UTC
I got an issue when I tried to call `.getValue()` of component in app with Vuetify. I have tried other components but the result was the same.
Can anyone let me know how to get through?

## Environments

- Chrome 89.0.4389.128 / macOS 11.2.3
- node: v14.15.5
- yarn: 1.22.10
- testcafe: 1.14.0
- testcafe-vue-selectors:  3.1.0
- vuetify: 2.4.2

## Test Codes
```js
const transfersTable = VueSelector('Transfer SingleAccountStatus v-data-table');
await t.hover(transfersTable); // OK

const transfersTableValues = await transfersTable.getVue(); // NOT OK
console.log(transfersTableValues);
```

![image](https://user-images.githubusercontent.com/16159767/115179394-33774280-a10e-11eb-98de-8031f378d4f2.png)

## Results
```sh
  1) An error occurred in getVue code:

      ReferenceError: _keys2 is not defined

      Browser: Chrome 89.0.4389.128 / macOS 11.2.3

         20 |    .click(proceedButton);
         21 |
         22 |  const transfersTable = VueSelector('Transfer SingleAccountStatus v-data');
         23 |  await t.hover(transfersTable);
         24 |
       > 25 |  const transfersTableValues = await transfersTable.getVue();
         26 |  console.log(transfersTableValues);
```

**Comment by miherlosev** [comment] 2021-04-21 07:26
Duplicate of https://github.com/DevExpress/testcafe-vue-selectors/issues/51

**Closed by miherlosev** 2021-04-21 07:26 UTC
Labels: STATE: Need response
