### ISSUE TITLE
Selector() failed to access "Row" of v-data-table of Vuetify

### ISSUE THREAD

**Issue by daenamkim** [DevExpress/testcafe-vue-selectors#53] opened 2021-04-19 04:17 UTC
Selector() failed to access `Row` component in v-data-table of Vuetify.

Related to #52

Can anyone help me out to resolve this?

## Environments

- Chrome 89.0.4389.128 / macOS 11.2.3
- node: v14.15.5
- yarn: 1.22.10
- testcafe: 1.14.0
- testcafe-vue-selectors:  3.1.0
- vuetify: 2.4.2

## Test Codes tried

```js
const transfersTableRow = VueSelector('Transfer SingleAccountStatus v-data-table row');
const transfersTableRow = VueSelector('Transfer SingleAccountStatus v-data-table row').nth(0);
const transfersTableRow = VueSelector('Transfer SingleAccountStatus v-data-table Row');
const transfersTableRow = VueSelector('Transfer SingleAccountStatus v-data-table Row').nth(0);
```

![image](https://user-images.githubusercontent.com/16159767/115179394-33774280-a10e-11eb-98de-8031f378d4f2.png)

## Results

```sh
 1) The specified selector does not match any element in the DOM tree.

       > | Selector([function])

      Browser: Chrome 89.0.4389.128 / macOS 11.2.3

         18 |    .typeText(amountInput, amount, { replace: true, paste: true })
         19 |    .click(transferButton)
         20 |    .click(proceedButton);
         21 |
         22 |  const transfersTableRow = VueSelector('Transfer SingleAccountStatus v-data-table row');
       > 23 |  await t.hover(transfersTableRow);
```

**Comment by miherlosev** [comment] 2021-04-21 07:25
Duplicate of https://github.com/DevExpress/testcafe-vue-selectors/issues/51

**Closed by miherlosev** 2021-04-21 07:25 UTC
Labels: STATE: Need response

**Comment by n0thingness** [comment] 2021-07-15 06:54
@miherlosev How is this a duplicate of #51? We're still running into this issue

**Comment by AlexKamaev** [comment] 2021-07-20 08:43
@n0thingness
Please update the `testcafe-vue-selectors` module to the latest version (v3.1.1) if you are not using the latest one.

If this issue is not related to #51 or #52, please share your example with us so that we can reproduce this behavior on our side.
